# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booktickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('tickets', models.IntegerField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=7)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('occassion', models.CharField(choices=[('birthday', 'Birthday'), ('marriage', 'Marriage'), ('holiday', 'Holiday'), ('meeting', 'Meeting')], default='holiday', max_length=20)),
            ],
        ),
    ]
