# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktickets',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
