# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_booktickets_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktickets',
            options={'ordering': ('-ordered',)},
        ),
        migrations.AddField(
            model_name='booktickets',
            name='ordered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booktickets',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
