# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190214_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktickets',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
